import { useEffect, useState, type FormEvent } from "react";
import { useAuth } from "../app/auth-context";
import { AppIcon } from "../components/AppIcon";
import { DashboardFilePicker } from "../components/DashboardFilePicker";
import { listProducts, createProduct, updateProduct, deleteProduct, uploadProductPhoto, type ProductWithId } from "../firebase/product-repo";
import { formatEuro } from "../domain/money";
import { getSalonAnalytics, type RankedMetric } from "../firebase/analytics-repo";

export function ProductsPage() {
  const { salonId } = useAuth(); const [items, setItems] = useState<ProductWithId[]>([]); const [titolo, setTitolo] = useState(""); const [descrizione, setDescrizione] = useState(""); const [prezzoEuro, setPrezzoEuro] = useState(""); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [warning, setWarning] = useState<string | null>(null); const [editingId, setEditingId] = useState<string | null>(null); const [metrics, setMetrics] = useState<RankedMetric[]>([]);
  async function reload(id: string) { const [products, analytics] = await Promise.all([listProducts(id), getSalonAnalytics(id, 30).catch(() => null)]); setItems(products); setMetrics(analytics?.products ?? []); }
  useEffect(() => { if (salonId) void reload(salonId); }, [salonId]);
  async function onSubmit(e: FormEvent) { e.preventDefault(); if (!salonId) return; setBusy(true); setWarning(null); try { const current = items.find((item) => item.id === editingId); const payload = { titolo, descrizione, prezzo: Math.round(parseFloat(prezzoEuro || "0") * 100), attivo: current?.attivo ?? true }; const id = editingId ?? await createProduct(salonId, payload); if (editingId) await updateProduct(salonId, editingId, payload); if (file) try { const photo = await uploadProductPhoto(salonId, id, file, file.name); await updateProduct(salonId, id, photo); } catch { setWarning("Prodotto salvato, ma la foto non è stata caricata."); } setTitolo(""); setDescrizione(""); setPrezzoEuro(""); setFile(null); setEditingId(null); await reload(salonId); } finally { setBusy(false); } }
  async function onDelete(id: string) { if (!salonId) return; await deleteProduct(salonId, id); await reload(salonId); }
  function startEdit(product: ProductWithId) { setEditingId(product.id); setTitolo(product.titolo); setDescrizione(product.descrizione ?? ""); setPrezzoEuro((product.prezzo / 100).toFixed(2)); setFile(null); document.querySelector(".entity-create")?.scrollIntoView({ behavior: "smooth", block: "center" }); }
  function cancelEdit() { setEditingId(null); setTitolo(""); setDescrizione(""); setPrezzoEuro(""); setFile(null); }
  async function toggleActive(product: ProductWithId) { if (!salonId) return; await updateProduct(salonId, product.id, { attivo: !product.attivo }); await reload(salonId); }
  return <section className="entity-page"><header className="dashboard-page-header"><div><span>Vendita</span><h2>Prodotti</h2><p>Catalogo retail con immagini, descrizioni e prezzi.</p></div><strong>{items.length}</strong></header>
    <div className="entity-card-grid">{items.map((product) => { const metric = metrics.find((item) => item.id === product.id); return <article className={`entity-card ${product.attivo ? "" : "is-inactive"}`} key={product.id}><div className="entity-card__media">{product.fotoUrl ? <img src={product.fotoUrl} alt="" /> : <AppIcon name="bag" size={34} />}<span className={product.attivo ? "is-active" : "is-off"}>{product.attivo ? "Disponibile" : "Nascosto"}</span></div><div className="entity-card__body"><small>Prodotto</small><h3>{product.titolo}</h3><p>{product.descrizione || "Nessuna descrizione inserita."}</p><a className="entity-card__performance" href={`/dashboard/statistiche?kind=prodotto&id=${product.id}`}><span><b>{metric?.current ?? 0}</b> venduti · € {formatEuro(metric?.revenue ?? 0)}</span><strong>{metric?.trend && metric.trend > 0 ? "+" : ""}{metric?.trend ?? 0}% →</strong></a><footer><span>Prezzo al cliente</span><strong>€ {formatEuro(product.prezzo)}</strong></footer><div className="entity-card__actions"><button type="button" onClick={() => startEdit(product)}>Modifica</button><button type="button" onClick={() => void toggleActive(product)}>{product.attivo ? "Nascondi" : "Attiva"}</button><button className="is-danger" type="button" onClick={() => void onDelete(product.id)}>Elimina</button></div></div></article>; })}</div>
    <form className="entity-create" onSubmit={onSubmit}><header><span>{editingId ? "Modifica" : "Nuovo"}</span><h3>{editingId ? "Modifica prodotto" : "Aggiungi prodotto"}</h3></header><div className="entity-create__grid"><label>Titolo<input value={titolo} onChange={(e) => setTitolo(e.target.value)} required /></label><label>Prezzo (€)<input type="number" min="0" step="0.01" value={prezzoEuro} onChange={(e) => setPrezzoEuro(e.target.value)} required /></label><DashboardFilePicker id="product-photo" label={editingId ? "Sostituisci foto (opzionale)" : "Foto"} file={file} onChange={setFile} /><label className="is-wide">Descrizione<textarea value={descrizione} onChange={(e) => setDescrizione(e.target.value)} /></label></div>{warning && <p role="alert">{warning}</p>}<div className="row"><button className="btn" type="submit" disabled={busy}>{busy ? "Salvataggio…" : editingId ? "Salva modifiche" : "Aggiungi prodotto"}</button>{editingId && <button className="btn btn--ghost" type="button" onClick={cancelEdit}>Annulla</button>}</div></form>
  </section>;
}
