import { useEffect, useState, type FormEvent } from "react";
import { useAuth } from "../app/auth-context";
import { AppIcon } from "../components/AppIcon";
import { DashboardFilePicker } from "../components/DashboardFilePicker";
import { createService, deleteService, listServices, updateService, uploadServicePhoto, type ServiceWithId } from "../firebase/service-repo";
import { formatEuro } from "../domain/money";
import { getSalonAnalytics, type RankedMetric } from "../firebase/analytics-repo";

export function ServicesPage() {
  const { salonId } = useAuth(); const [items, setItems] = useState<ServiceWithId[]>([]);
  const [titolo, setTitolo] = useState(""); const [descrizione, setDescrizione] = useState(""); const [prezzoEuro, setPrezzoEuro] = useState(""); const [durata, setDurata] = useState(""); const [file, setFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false); const [warning, setWarning] = useState<string | null>(null); const [editingId, setEditingId] = useState<string | null>(null); const [metrics, setMetrics] = useState<RankedMetric[]>([]);
  async function reload(id: string) { const [services, analytics] = await Promise.all([listServices(id), getSalonAnalytics(id, 30).catch(() => null)]); setItems(services); setMetrics(analytics?.services ?? []); }
  useEffect(() => { if (salonId) void reload(salonId); }, [salonId]);
  async function onSubmit(event: FormEvent) { event.preventDefault(); if (!salonId) return; setBusy(true); setWarning(null); try {
    const current = items.find((item) => item.id === editingId); const payload = { titolo, descrizione, prezzo: Math.round(Number.parseFloat(prezzoEuro || "0") * 100), durataMin: Number.parseInt(durata || "0", 10), attivo: current?.attivo ?? true };
    const id = editingId ?? await createService(salonId, payload); if (editingId) await updateService(salonId, editingId, payload);
    if (file) try { const photo = await uploadServicePhoto(salonId, id, file, file.name); await updateService(salonId, id, photo); } catch { setWarning("Servizio creato, ma la foto non è stata caricata."); }
    setTitolo(""); setDescrizione(""); setPrezzoEuro(""); setDurata(""); setFile(null); setEditingId(null); await reload(salonId);
  } finally { setBusy(false); } }
  async function onDelete(id: string) { if (!salonId) return; await deleteService(salonId, id); await reload(salonId); }
  function startEdit(service: ServiceWithId) { setEditingId(service.id); setTitolo(service.titolo); setDescrizione(service.descrizione ?? ""); setPrezzoEuro((service.prezzo / 100).toFixed(2)); setDurata(String(service.durataMin)); setFile(null); document.querySelector(".entity-create")?.scrollIntoView({ behavior: "smooth", block: "center" }); }
  function cancelEdit() { setEditingId(null); setTitolo(""); setDescrizione(""); setPrezzoEuro(""); setDurata(""); setFile(null); }
  async function toggleActive(service: ServiceWithId) { if (!salonId) return; await updateService(salonId, service.id, { attivo: !service.attivo }); await reload(salonId); }
  return <section className="entity-page"><header className="dashboard-page-header"><div><span>Catalogo</span><h2>Servizi</h2><p>Un colpo d’occhio su proposta, durata e prezzo.</p></div><strong>{items.length}</strong></header>
    <div className="entity-card-grid">{items.map((service) => { const metric = metrics.find((item) => item.id === service.id); return <article className={`entity-card ${service.attivo ? "" : "is-inactive"}`} key={service.id}><div className="entity-card__media">{service.fotoUrl ? <img src={service.fotoUrl} alt="" /> : <AppIcon name="scissors" size={34} />}<span className={service.attivo ? "is-active" : "is-off"}>{service.attivo ? "Attivo" : "Non attivo"}</span></div><div className="entity-card__body"><small>Servizio</small><h3>{service.titolo}</h3><p>{service.descrizione || "Nessuna descrizione inserita."}</p><a className="entity-card__performance" href={`/dashboard/statistiche?kind=servizio&id=${service.id}`}><span><b>{metric?.current ?? 0}</b> richieste · € {formatEuro(metric?.revenue ?? 0)}</span><strong>{metric?.trend && metric.trend > 0 ? "+" : ""}{metric?.trend ?? 0}% →</strong></a><footer><span><AppIcon name="clock" size={15} /> {service.durataMin} min</span><strong>€ {formatEuro(service.prezzo)}</strong></footer><div className="entity-card__actions"><button type="button" onClick={() => startEdit(service)}>Modifica</button><button type="button" onClick={() => void toggleActive(service)}>{service.attivo ? "Disattiva" : "Attiva"}</button><button className="is-danger" type="button" onClick={() => void onDelete(service.id)}>Elimina</button></div></div></article>; })}</div>
    <form className="entity-create" onSubmit={onSubmit}><header><span>{editingId ? "Modifica" : "Nuovo"}</span><h3>{editingId ? "Modifica servizio" : "Aggiungi servizio"}</h3></header><div className="entity-create__grid"><label>Titolo<input value={titolo} onChange={(e) => setTitolo(e.target.value)} required /></label><label>Durata (min)<input type="number" min="5" step="5" value={durata} onChange={(e) => setDurata(e.target.value)} required /></label><label>Prezzo (€)<input type="number" min="0" step="0.01" value={prezzoEuro} onChange={(e) => setPrezzoEuro(e.target.value)} required /></label><DashboardFilePicker id="service-photo" label={editingId ? "Sostituisci foto (opzionale)" : "Foto"} file={file} onChange={setFile} /><label className="is-wide">Descrizione<textarea value={descrizione} onChange={(e) => setDescrizione(e.target.value)} /></label></div>{warning && <p role="alert">{warning}</p>}<div className="row"><button className="btn" type="submit" disabled={busy}>{busy ? "Salvataggio…" : editingId ? "Salva modifiche" : "Aggiungi servizio"}</button>{editingId && <button className="btn btn--ghost" type="button" onClick={cancelEdit}>Annulla</button>}</div></form>
  </section>;
}
