import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import { AppIcon } from "./AppIcon";
import type { TicketAttachment, TicketChannel, TicketMessage, TicketPriority, TicketStatus } from "../domain/models";
import { createTicket, listMyTickets, listPlatformTickets, listSalonTickets, listTicketMessages, sendTicketMessage, updateTicketStatus, type TicketMessageWithId, type TicketWithId } from "../firebase/ticket-repo";
import { prepareTicketAttachment, recordScreenClip } from "../utils/ticket-media";
import "./ticket-center.css";

type TicketMode = "customer" | "salon-customer" | "salon-platform" | "platform";
const MAX_MESSAGE_MEDIA_BYTES = 680_000;
const STATUS_LABEL: Record<TicketStatus, string> = { aperto: "Aperto", in_lavorazione: "In lavorazione", risolto: "Risolto", chiuso: "Chiuso" };
const PRIORITY_LABEL: Record<TicketPriority, string> = { bassa: "Bassa", normale: "Normale", alta: "Alta" };

function MediaControls({ files, onChange, recording, onRecord }: { files: TicketAttachment[]; onChange: (value: TicketAttachment[]) => void; recording: boolean; onRecord: () => void }) {
  const [error, setError] = useState<string | null>(null);
  async function pick(event: ChangeEvent<HTMLInputElement>) { setError(null); const selected = [...(event.target.files ?? [])].slice(0, 2 - files.length); try { const next = await Promise.all(selected.map(prepareTicketAttachment)); if ([...files, ...next].reduce((sum, item) => sum + item.dimensione, 0) > MAX_MESSAGE_MEDIA_BYTES) throw new Error("Gli allegati del messaggio superano complessivamente 680 KB."); onChange([...files, ...next]); } catch (caught) { setError(caught instanceof Error ? caught.message : "Allegato non valido."); } event.target.value = ""; }
  return <div className="ticket-media"><div className="ticket-media__buttons"><label><AppIcon name="paperclip" size={17} />Allega file<input type="file" accept="image/*,video/webm,video/mp4" multiple onChange={(event) => void pick(event)} disabled={files.length >= 2} /></label><button type="button" onClick={onRecord} disabled={recording || files.length >= 2}><AppIcon name="video" size={17} />{recording ? "Registrazione (max 15 s)…" : "Registra schermo"}</button></div>{files.length > 0 && <div className="ticket-media__files">{files.map((file, index) => <span key={`${file.nome}-${index}`}><b>{file.nome}</b><small>{Math.ceil(file.dimensione / 1024)} KB</small><button type="button" aria-label={`Rimuovi ${file.nome}`} onClick={() => onChange(files.filter((_, itemIndex) => itemIndex !== index))}>×</button></span>)}</div>}{error && <p role="alert">{error}</p>}</div>;
}

function AttachmentPreview({ attachment }: { attachment: TicketAttachment }) {
  return attachment.tipo.startsWith("image/") ? <a className="ticket-attachment" href={attachment.dataUrl} target="_blank" rel="noreferrer"><img src={attachment.dataUrl} alt={attachment.nome} /><span>Apri immagine</span></a> : attachment.tipo.startsWith("video/") ? <video className="ticket-attachment-video" src={attachment.dataUrl} controls aria-label={attachment.nome} /> : null;
}

export function TicketCenter({ mode, salonId, viewerName }: { mode: TicketMode; salonId?: string | null; viewerName: string }) {
  const channel: TicketChannel = mode === "customer" || mode === "salon-customer" ? "cliente_salone" : "salone_piattaforma";
  const canCreate = mode === "customer" || mode === "salon-platform"; const canManage = mode === "salon-customer" || mode === "platform";
  const senderRole: TicketMessage["senderRole"] = mode === "customer" ? "cliente" : mode === "platform" ? "piattaforma" : "salone";
  const [tickets, setTickets] = useState<TicketWithId[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [messages, setMessages] = useState<TicketMessageWithId[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [showCreate, setShowCreate] = useState(false);
  const [subject, setSubject] = useState(""); const [category, setCategory] = useState(channel === "cliente_salone" ? "Prenotazione" : "Problema tecnico"); const [priority, setPriority] = useState<TicketPriority>("normale"); const [body, setBody] = useState(""); const [files, setFiles] = useState<TicketAttachment[]>([]); const [reply, setReply] = useState(""); const [replyFiles, setReplyFiles] = useState<TicketAttachment[]>([]); const [recording, setRecording] = useState<"create" | "reply" | null>(null);
  const selected = useMemo(() => tickets.find((ticket) => ticket.id === selectedId) ?? null, [tickets, selectedId]);

  async function reload(preferredId?: string) { setLoading(true); setError(null); try { const next = mode === "platform" ? await listPlatformTickets() : mode === "salon-customer" && salonId ? await listSalonTickets(salonId, channel) : await listMyTickets(channel, salonId ?? undefined); setTickets(next); const nextId = preferredId ?? selectedId ?? next[0]?.id ?? null; setSelectedId(nextId); if (nextId) setMessages(await listTicketMessages(nextId)); else setMessages([]); } catch { setError("Non è stato possibile caricare i ticket."); } finally { setLoading(false); } }
  useEffect(() => { void reload(); }, [mode, salonId]);
  useEffect(() => { if (!selectedId) { setMessages([]); return; } void listTicketMessages(selectedId).then(setMessages).catch(() => setError("Conversazione non disponibile.")); }, [selectedId]);

  async function capture(target: "create" | "reply") { setRecording(target); setError(null); try { const clip = await recordScreenClip(); const prepared = await prepareTicketAttachment(clip); const current = target === "create" ? files : replyFiles; if (current.reduce((sum, item) => sum + item.dimensione, 0) + prepared.dimensione > MAX_MESSAGE_MEDIA_BYTES) throw new Error("La registrazione è troppo grande. Registra una sequenza più breve."); if (target === "create") setFiles([...current, prepared].slice(0, 2)); else setReplyFiles([...current, prepared].slice(0, 2)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Registrazione non riuscita."); } finally { setRecording(null); } }
  async function submitNew(event: FormEvent) { event.preventDefault(); if (!salonId || (!body.trim() && files.length === 0)) return; setBusy(true); setError(null); try { const id = await createTicket({ salonId, channel, oggetto: subject, categoria: category, priorita: priority, requesterName: viewerName, testo: body, allegati: files }); setSubject(""); setBody(""); setFiles([]); setShowCreate(false); await reload(id); } catch { setError("Non è stato possibile aprire il ticket."); } finally { setBusy(false); } }
  async function submitReply(event: FormEvent) { event.preventDefault(); if (!selected || (!reply.trim() && replyFiles.length === 0)) return; setBusy(true); setError(null); try { await sendTicketMessage({ ticket: selected, senderName: viewerName, senderRole, testo: reply, allegati: replyFiles }); setReply(""); setReplyFiles([]); await reload(selected.id); } catch { setError("Non è stato possibile inviare la risposta."); } finally { setBusy(false); } }
  async function setStatus(status: TicketStatus) { if (!selected) return; setBusy(true); try { await updateTicketStatus(selected.id, status); await reload(selected.id); } catch { setError("Stato non aggiornato."); } finally { setBusy(false); } }

  return <section className="ticket-center">
    <div className="ticket-center__toolbar"><div><span>{tickets.length} ticket</span><strong>{tickets.filter((ticket) => ticket.stato === "aperto" || ticket.stato === "in_lavorazione").length} da seguire</strong></div>{canCreate && <button type="button" onClick={() => setShowCreate((value) => !value)}><AppIcon name={showCreate ? "close" : "plus"} size={17} />{showCreate ? "Annulla" : "Apri ticket"}</button>}</div>
    {showCreate && <form className="ticket-create" onSubmit={submitNew}><header><span>Nuova richiesta</span><h3>{channel === "cliente_salone" ? "Come possiamo aiutarti?" : "Contatta il team Salon Suite"}</h3></header><div className="ticket-create__fields"><label>Oggetto<input value={subject} onChange={(event) => setSubject(event.target.value)} placeholder="Descrivi il problema in poche parole" required /></label><label>Categoria<select value={category} onChange={(event) => setCategory(event.target.value)}>{(channel === "cliente_salone" ? ["Prenotazione", "Ordine", "Fidelity", "Servizi", "Altro"] : ["Problema tecnico", "Account e accesso", "Configurazione", "Fatturazione", "Richiesta funzionalità"]).map((item) => <option key={item}>{item}</option>)}</select></label><label>Priorità<select value={priority} onChange={(event) => setPriority(event.target.value as TicketPriority)}><option value="bassa">Bassa</option><option value="normale">Normale</option><option value="alta">Alta</option></select></label></div><label className="ticket-create__body">Descrizione<textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="Indica cosa è successo e cosa ti aspettavi…" required={files.length === 0} /></label><MediaControls files={files} onChange={setFiles} recording={recording === "create"} onRecord={() => void capture("create")} />{error && <p className="ticket-error" role="alert">{error}</p>}<button className="ticket-submit" disabled={busy}>{busy ? "Apertura…" : "Apri richiesta"}</button></form>}
    <div className="ticket-workspace"><aside className="ticket-list">{loading ? <div className="ticket-empty">Caricamento…</div> : tickets.length === 0 ? <div className="ticket-empty"><AppIcon name="ticket" size={30} /><strong>Nessun ticket</strong><p>{canCreate ? "Apri una richiesta quando hai bisogno di assistenza." : "Le nuove richieste compariranno qui."}</p></div> : tickets.map((ticket) => <button type="button" className={ticket.id === selectedId ? "is-selected" : ""} onClick={() => setSelectedId(ticket.id)} key={ticket.id}><div><span className={`ticket-status is-${ticket.stato}`}>{STATUS_LABEL[ticket.stato]}</span><small>{new Intl.DateTimeFormat("it-IT", { day: "numeric", month: "short" }).format(ticket.updatedAtMs)}</small></div><strong>{ticket.oggetto}</strong><p>{ticket.lastMessage || "Allegato"}</p><footer><span>{ticket.requesterName}</span><b className={`is-${ticket.priorita}`}>{PRIORITY_LABEL[ticket.priorita]}</b></footer></button>)}</aside>
      <article className="ticket-thread">{!selected ? <div className="ticket-empty"><AppIcon name="send" size={30} /><strong>Seleziona una conversazione</strong><p>Messaggi e allegati appariranno qui.</p></div> : <><header><div><span>{selected.categoria} · #{selected.id.slice(0, 6).toUpperCase()}</span><h3>{selected.oggetto}</h3><p>Aperto da {selected.requesterName}</p></div><span className={`ticket-status is-${selected.stato}`}>{STATUS_LABEL[selected.stato]}</span></header>{canManage && <div className="ticket-thread__actions"><button type="button" disabled={busy || selected.stato === "in_lavorazione"} onClick={() => void setStatus("in_lavorazione")}>Prendi in carico</button><button type="button" disabled={busy || selected.stato === "risolto"} onClick={() => void setStatus("risolto")}>Segna risolto</button><button type="button" disabled={busy || selected.stato === "chiuso"} onClick={() => void setStatus("chiuso")}>Chiudi</button></div>}<div className="ticket-messages">{messages.map((message) => <section className={message.senderRole === senderRole ? "is-own" : ""} key={message.id}><header><strong>{message.senderName}</strong><span>{new Intl.DateTimeFormat("it-IT", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }).format(message.createdAtMs)}</span></header>{message.testo && <p>{message.testo}</p>}{message.allegati?.map((attachment, index) => <AttachmentPreview attachment={attachment} key={`${attachment.nome}-${index}`} />)}</section>)}</div><form className="ticket-reply" onSubmit={submitReply}><label>Rispondi<textarea value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Scrivi un messaggio…" required={replyFiles.length === 0} /></label><MediaControls files={replyFiles} onChange={setReplyFiles} recording={recording === "reply"} onRecord={() => void capture("reply")} />{error && <p className="ticket-error" role="alert">{error}</p>}<button className="ticket-submit" disabled={busy}><AppIcon name="send" size={16} />{busy ? "Invio…" : "Invia risposta"}</button></form></>}</article>
    </div>
  </section>;
}
